import React from 'react';
import { ModelEdit } from '@/components/model/model-edit';
import InputError from '@/components/ui/input-error';
import {Input} from '@/components/ui/input';
import {Select} from '@/components/ui/select';

// User interface matching our Prisma schema
interface User {
  id: string;
  email: string;
  name: string | null;
  picture: string | null;
  role: string;
  createdAt?: string;
  updatedAt?: string;
}

// Form rendering function for user creation/editing
const renderUserForm = (
  data: User,
  setData: (key: string, value: any) => void,
  errors: Partial<Record<string, string>>,
  processing: boolean,
  readonly?: boolean
) => {
  return (
    <div className="space-y-4">
      {/* Email Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Email *</span>
        </label>
        <Input
          type="email"
          color={errors?.email ? 'error' : 'default'}
          className="w-full"
          value={data.email || ''}
          onChange={(e) => setData('email', e.target.value)}
          disabled={processing || readonly}
          placeholder="Enter email address"
          required
        />
        <InputError message={errors?.email} />
      </div>

      {/* Name Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Full Name</span>
        </label>
        <Input
          type="text"
          color={errors?.name ? 'error' : 'default'}
          className="w-full"
          value={data.name || ''}
          onChange={(e) => setData('name', e.target.value)}
          disabled={processing || readonly}
          placeholder="Enter full name (optional)"
        />
        <InputError message={errors?.name} />
      </div>

      {/* Role Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Role *</span>
        </label>
        <Select
          color={errors?.role ? 'error' : 'default'}
          className="w-full"
          value={data.role || 'user'}
          onChange={(e) => setData('role', e.target.value)}
          disabled={processing || readonly}
          required
        >
          <option value="user">User</option>
          <option value="admin">Admin</option>
        </Select>
        <InputError message={errors?.role} />
        <label className="label">
          <span className="label-text-alt">Users can manage their own data, admins can manage all system data.</span>
        </label>
      </div>

      {/* Profile Picture URL */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Profile Picture URL</span>
        </label>
        <Input
          type="url"
          color={errors?.picture ? 'error' : 'default'}
          className="w-full"
          value={data.picture || ''}
          onChange={(e) => setData('picture', e.target.value)}
          disabled={processing || readonly}
          placeholder="https://example.com/avatar.jpg (optional)"
        />
        <InputError message={errors?.picture} />
        <label className="label">
          <span className="label-text-alt">Profile pictures are typically managed through Google OAuth.</span>
        </label>
      </div>

      {readonly && data.createdAt && (
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Created At</span>
          </label>
          <Input
            type="text"
            className="w-full"
            value={new Date(data.createdAt).toLocaleString()}
            disabled
          />
        </div>
      )}
    </div>
  );
};

export default function CreateUserPage() {
  const newUser: User = {
    id: '', // Will be generated by the server
    email: '',
    name: null,
    picture: null,
    role: 'user'
  };

  return (
    <ModelEdit<User>
      title="User"
      item={newUser}
      backRoute="/dashboard/users"
      submitRoute="/api/users"
      method="post"
      renderForm={renderUserForm}
    />
  );
}