import React from 'react';
import { ModelEdit } from '@/components/model/model-edit';
import InputError from '@/components/ui/input-error';
import {Input} from '@/components/ui/input';
import {Select} from '@/components/ui/select';

// AllowedEmail interface matching our Prisma schema
interface AllowedEmail {
  id: string;
  email: string | null;
  domain: string | null;
  type: string;
  createdAt?: string;
}

// Form rendering function for allowed email creation/editing
const renderAllowedEmailForm = (
  data: AllowedEmail,
  setData: (key: string, value: any) => void,
  errors: Partial<Record<string, string>>,
  processing: boolean,
  readonly?: boolean
) => {
  return (
    <div className="space-y-4">
      {/* Type Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Type *</span>
        </label>
        <Select
          color={errors?.type ? 'error' : 'default'}
          className="w-full"
          value={data.type || 'email'}
          onChange={(e) => {
            setData('type', e.target.value);
            // Clear the other field when type changes
            if (e.target.value === 'email') {
              setData('domain', null);
            } else {
              setData('email', null);
            }
          }}
          disabled={processing || readonly}
          required
        >
          <option value="email">Specific Email</option>
          <option value="domain">Domain Pattern</option>
        </Select>
        <InputError message={errors?.type} />
        <label className="label">
          <span className="label-text-alt">
            Choose "Specific Email" to allow one email address, or "Domain Pattern" to allow all emails from a domain.
          </span>
        </label>
      </div>

      {/* Email Field - only show when type is 'email' */}
      {data.type === 'email' && (
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Email Address *</span>
          </label>
          <Input
            type="email"
            color={errors?.email ? 'error' : 'default'}
            className="w-full"
            value={data.email || ''}
            onChange={(e) => setData('email', e.target.value)}
            disabled={processing || readonly}
            placeholder="user@example.com"
            required
          />
          <InputError message={errors?.email} />
          <label className="label">
            <span className="label-text-alt">Enter the specific email address to allow access.</span>
          </label>
        </div>
      )}

      {/* Domain Field - only show when type is 'domain' */}
      {data.type === 'domain' && (
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Domain Pattern *</span>
          </label>
          <Input
            type="text"
            color={errors?.domain ? 'error' : 'default'}
            className="w-full"
            value={data.domain || ''}
            onChange={(e) => setData('domain', e.target.value)}
            disabled={processing || readonly}
            placeholder="example.com or @example.com"
            required
          />
          <InputError message={errors?.domain} />
          <label className="label">
            <span className="label-text-alt">
              Enter a domain like "example.com" to allow all emails from that domain (e.g., user@example.com, admin@example.com).
            </span>
          </label>
        </div>
      )}

      {readonly && data.createdAt && (
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Created At</span>
          </label>
          <Input
            type="text"
            className="w-full"
            value={new Date(data.createdAt).toLocaleString()}
            disabled
          />
        </div>
      )}
    </div>
  );
};

export default function CreateAllowedEmailPage() {
  const newAllowedEmail: AllowedEmail = {
    id: '', // Will be generated by the server
    email: null,
    domain: null,
    type: 'email' // Default to email type
  };

  return (
    <ModelEdit<AllowedEmail>
      title="Allowed Email"
      item={newAllowedEmail}
      backRoute="/dashboard/allowed-emails"
      submitRoute="/api/allowed-emails"
      method="post"
      renderForm={renderAllowedEmailForm}
    />
  );
}