import React from 'react';
import { ModelEdit } from '@/components/model/model-edit';
import InputError from '@/components/ui/input-error';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';

// Item interface matching our dashboard page structure
interface Item {
  id: string;
  name: string;
  description: string | null;
  price: number;
  quantity: number;
  category: string;
  createdAt?: string;
  updatedAt?: string;
}

// Form rendering function for item creation/editing
const renderItemForm = (
  data: Item,
  setData: (key: string, value: any) => void,
  errors: Partial<Record<string, string>>,
  processing: boolean,
  readonly?: boolean
) => {
  return (
    <div className="space-y-4">
      {/* Name Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Name *</span>
        </label>
        <Input
          type="text"
          color={errors?.name ? 'error' : 'default'}
          className="w-full"
          value={data.name || ''}
          onChange={(e) => setData('name', e.target.value)}
          disabled={processing || readonly}
          placeholder="Enter item name"
          required
        />
        <InputError message={errors?.name} />
      </div>

      {/* Description Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Description</span>
        </label>
        <Textarea
          color={errors?.description ? 'error' : 'default'}
          className="w-full"
          value={data.description || ''}
          onChange={(e) => setData('description', e.target.value)}
          disabled={processing || readonly}
          placeholder="Enter item description (optional)"
          rows={3}
        />
        <InputError message={errors?.description} />
      </div>

      {/* Price and Quantity Row */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Price Field */}
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Price *</span>
          </label>
          <div className="relative">
            <span className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500">$</span>
            <Input
              type="number"
              step="0.01"
              min="0"
              color={errors?.price ? 'error' : 'default'}
              className="w-full pl-8"
              value={data.price || ''}
              onChange={(e) => setData('price', parseFloat(e.target.value) || 0)}
              disabled={processing || readonly}
              placeholder="0.00"
              required
            />
          </div>
          <InputError message={errors?.price} />
        </div>

        {/* Quantity Field */}
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Quantity *</span>
          </label>
          <Input
            type="number"
            min="0"
            color={errors?.quantity ? 'error' : 'default'}
            className="w-full"
            value={data.quantity || ''}
            onChange={(e) => setData('quantity', parseInt(e.target.value) || 0)}
            disabled={processing || readonly}
            placeholder="0"
            required
          />
          <InputError message={errors?.quantity} />
        </div>
      </div>

      {/* Category Field */}
      <div className="form-control w-full">
        <label className="label">
          <span className="label-text">Category</span>
        </label>
        <Input
          type="text"
          color={errors?.category ? 'error' : 'default'}
          className="w-full"
          value={data.category || ''}
          onChange={(e) => setData('category', e.target.value)}
          disabled={processing || readonly}
          placeholder="Enter item category (optional)"
        />
        <InputError message={errors?.category} />
        <label className="label">
          <span className="label-text-alt">Categories help organize your inventory.</span>
        </label>
      </div>

      {readonly && data.createdAt && (
        <div className="form-control w-full">
          <label className="label">
            <span className="label-text">Created At</span>
          </label>
          <Input
            type="text"
            className="w-full"
            value={new Date(data.createdAt).toLocaleString()}
            disabled
          />
        </div>
      )}
    </div>
  );
};

export default function CreateItemPage() {
  const newItem: Item = {
    id: '', // Will be generated by the server
    name: '',
    description: null,
    price: 0,
    quantity: 0,
    category: ''
  };

  return (
    <ModelEdit<Item>
      title="Item"
      item={newItem}
      backRoute="/dashboard"
      submitRoute="/api/items"
      method="post"
      renderForm={renderItemForm}
    />
  );
}